version: '3.9'
services:

  db_w:
    image: postgres:latest
    container_name: db_warehouse
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_w:/usr/lib/postgresql/data
    networks:
      - warehouse
    ports:
      - '7001:5432'

  warehouse:
    build: ./../warehouse
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./../warehouse/:/usr/src/warehouse/
    networks:
      - warehouse
    ports:
      - '8000:8000'
    depends_on:
      - db_w

  db_s:
    image: postgres:latest
    container_name: db_shop
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_s:/usr/lib/postgresql/data
    networks:
      - shop
    ports:
      - '7000:5432'

  red:
    image: redis:6.2.6
    container_name: red_for_shop
    networks:
      - shop

  rabb:
    image: rabbitmq:latest
    container_name: rabbit
    networks:
      - shop

  celr:
    image: celery:4.0.2
    container_name: celery
    networks:
      - shop
      - warehouse
    depends_on:
      - rabb

  shop:
    build: ./../shop
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./../shop:/usr/src/shop
    networks:
    - shop
    ports:
      - '8001:8001'
    depends_on:
      - db_s

networks:
  warehouse:
  shop:

volumes:
  db_s:
  db_w:
