version: '3.9'
services:

  db_w:
    image: postgres:latest
    container_name: db_warehouse
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_w:/usr/lib/postgresql/data
    networks:
      - warehouse
    ports:
      - '7001:5432'

  warehouse:
    build: ./../warehouse
    container_name: warehouse_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./../warehouse/:/usr/src/warehouse/
    networks:
      - warehouse
    ports:
      - '8000:8000'
    depends_on:
      - db_w

  db_s:
    image: postgres:latest
    container_name: db_shop
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_s:/usr/lib/postgresql/data
    networks:
      - shop
    ports:
      - '7000:5432'

  redis:
    image: redis:6.2.6
    container_name: red
    command: redis-server
    networks:
      - shop
    ports:
      - '6400:6379'

  rabbit:
    image: rabbitmq:latest
    container_name: rabbit_cont
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - shop
    ports:
       - '15673:15672'

  celery:
    build: ./../shop
    container_name: celery
    command: 'celery -A core_shop worker -l INFO'
    networks:
      - shop
      - warehouse
    depends_on:
      - rabb
      - redis
      - shop
    ports:
      - '5500:5500'

  shop:
    build: ./../shop
    container_name: shop_cont
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./../shop:/usr/src/shop
    networks:
      - shop
    ports:
      - '8001:8001'
    depends_on:
      - db_s

networks:
  warehouse:
  shop:

volumes:
  db_s:
  db_w:
