# Generated by Django 3.2.8 on 2021-10-28 02:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='рейтинг')),
                ('authors', models.CharField(max_length=300, verbose_name='авторы')),
                ('pubdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'authors')},
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='значение не может быть отрицательным')])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wBooks.book')),
            ],
        ),
    ]
