# Generated by Django 3.2.8 on 2021-11-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Noname', max_length=300, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена')),
                ('rating', models.FloatField(blank=True, default=0, null=True, verbose_name='рейтинг')),
                ('pubdate', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('authors', models.ManyToManyField(related_name='авторы', to='catalog.Author')),
            ],
        ),
    ]
