# Generated by Django 3.2.8 on 2021-10-28 02:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wBooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MinValueValidator(0, 'Значение не может быть отрицательным')], verbose_name='сумма заказа')),
                ('status', models.CharField(choices=[('UNDF', 'undefined'), ('SEND', 'sended'), ('SBMT', 'submitted'), ('PAID', 'paid'), ('SHIP', 'shipped'), ('DLVR', 'delivered')], default='UNDF', max_length=4, verbose_name='статус заказа')),
                ('pub_date', models.DateTimeField()),
                ('books', models.ManyToManyField(to='wBooks.Book')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
